title: Gradient Ascent Tutoring
logo: /assets/img/logo.png
description:  Math, Statistics, and Machine Learning Tutoring Services with Iordan Ganev.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
email: inquiries@grad-ascent.com
google_analytics: G-DMTGHZ9XBE