title: Gradient Ascent Tutoring
logo: /assets/img/logo.png
description:  Expert Guidance in Math, Statistics, and Machine Learning.
show_downloads: false
theme: jekyll-theme-minimal
email: inquiries@grad-ascent.com
google_analytics: G-DMTGHZ9XBE
rate: 60
free_minutes: 30